all: part0 part3b part5

part0: part0.c nqueens_library.c
        cc -o part0 part0.c nqueens_library.c

part3b: part3b.c nqueens_library.c
        cc -o part3b part3b.c nqueens_library.c

part5: part5.c nqueens_library.c
        cc -pthread -o part5 part5.c nqueens_library.c
